### ISSUE TITLE
Error: ENOENT: no such file or directory, stat 'C:\C:\Users\......

### ISSUE THREAD

**Issue by hakanols** [vanillaes/tape-es#3]
Running on a Windows machine. Getting a strange error. Am I doing something wrong?

C:\Users\Peter\Desktop\Hakan\tape>npm install -g tape-es
C:\Users\Peter\AppData\Roaming\npm\tape-es -> C:\Users\Peter\AppData\Roaming\npm\node_modules\tape-es\bin\tape-es
C:\Users\Peter\AppData\Roaming\npm\tape-watch-es -> C:\Users\Peter\AppData\Roaming\npm\node_modules\tape-es\bin\tape-watch-es
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\tape-es\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ tape-es@1.1.7
added 56 packages from 36 contributors in 5.571s

C:\Users\Peter\Desktop\Hakan\tape>tape-es
(node:20788) ExperimentalWarning: The ESM module loader is experimental.
[Error: ENOENT: no such file or directory, stat 'C:\C:\Users\Peter\AppData\Roaming\npm\node_modules\tape-es\package.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\C:\\Users\\Peter\\AppData\\Roaming\\npm\\node_modules\\tape-es\\package.json'
}

C:\Users\Peter\Desktop\Hakan\tape>node -v
v13.8.0

C:\Users\Peter\Desktop\Hakan\tape>npm -v
6.13.6

**Comment by hakanols** [comment]
I run with no arguments. I get the same error any way. The path look suspicious. It starts with " 'C:\C:\User..."

**Comment by evanplaice** [comment]
It's being caused by the path lookup here

https://github.com/vanillaes/tape-es/blob/e976b35fcb8dcb7f58664dfc7f876dd9033beda2/src/util/readPkg.js#L5

Short answer, platform-specific globals like `__dirname` aren't supported in ES modules. I'm still getting a feel for the alternative.

I just published a fix in v1.1.8. Let me know if that works.

**Comment by hakanols** [comment]
Excellent. I can test on Sunday.  Will return with an answer then.

**Comment by hakanols** [comment]
All up and running now. Thanks

**Comment by evanplaice** [comment]
Yes! That answers that question. Thanks for taking the time to follow up.

**Comment by evanplaice** [comment]
Fixed in [v1.1.8](https://github.com/vanillaes/tape-es/releases/tag/v1.1.8)
