### ISSUE TITLE
Support Node-12.18.2 LTS

### ISSUE THREAD

**Issue by Gozala** [vanillaes/tape-es#5]
It works fine with current LTS version of node 12.18.2. Can the requirement of node 14 be loosened up ?

**Comment by evanplaice** [comment]
I'm not really sure the best way to deal with this. It should work with >=13.12 as well

I put 14 as a baseline because it'll be the next LTS and it doesn't output experimental warning.

**Comment by Gozala** [comment]
I end up using my fork that just changes engine version to ^12.18.2

https://github.com/Gozala/tape-es/commit/25e0fb1636f5e14a7ac77f3964bea4a834caa1c8

I do see warning, but it works without problems.

I would much rather allow users to choose if they’re ok with warnings than prevent using without forking

**Comment by Gozala** [comment]
Just created pull #6 In case supporting it would be decided

**Comment by evanplaice** [comment]
Cool. I was under the impression that the warnings were going to remain in the 12.x line

I had users complain about the warnings before.

I'll merge this next time I'm in front of my computer.

**Comment by Gozala** [comment]
> Cool. I was under the impression that the warnings were going to remain in the 12.x line

Yes warnings are still there about ESM support been experimental. But I’d rather see warnings on TLS than not support it at all
